version: '3'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: zip_codes_areas
      POSTGRES_USER: zip_codes_areas
      POSTGRES_PASSWORD: insecure
    ports:
      - "5444:5432"
  importer:
    build: .
    links:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: zip_codes_areas
      DATABASE_USER: zip_codes_areas
      DATABASE_PASSWORD: insecure
      DATABASE_SCHEMA:
      DATABASE_PORT: 5432
    command: >
      bash -c "/app/import.sh"  
